#!/bin/sh
exec 2>&1

PERL=/home/babyry/perl5/perlbrew/perls/perl-5.16.3/bin/perl
DAEMON=/home/babyry/BabyryServer5001/script/daemon/image_send_to_s3.pl

. /home/babyry/aws/credential

exec \
  envdir ./env \
  $PERL $DAEMON
